"""config.py — paths, env loading, and shared constants."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
CACHE_DIR = DATA_DIR / "cache"
MODELS_DIR = PROJECT_ROOT / "models"
FRONTEND_DIST_DIR = PROJECT_ROOT / "frontend" / "dist"

# Public, password-gated read-only deployment (see api/auth.py) — unset/false
# everywhere else, which reproduces this app's original private-network-only
# behavior exactly (api/main.py's own CORS comment). Never set GUEST_PASSWORD
# in a committed file; it's provided as a hosting-platform secret.
PUBLIC_MODE = os.getenv("PUBLIC_MODE", "false").lower() == "true"
GUEST_PASSWORD = os.getenv("GUEST_PASSWORD")

JOLPICA_CACHE_DIR = CACHE_DIR / "jolpica"
FASTF1_CACHE_DIR = CACHE_DIR / "fastf1"
OPENF1_CACHE_DIR = CACHE_DIR / "openf1"
OPEN_METEO_CACHE_DIR = CACHE_DIR / "open_meteo"

CURRENT_SEASON = 2026  # bump each January

JOLPICA_BASE_URL = "https://api.jolpi.ca/ergast/f1"
JOLPICA_USER_AGENT = os.getenv(
    "JOLPICA_USER_AGENT", "F1Predictor/0.1 (personal project)"
)
# jolpica-f1 rate limit: 4 req/s, 500 req/hour, unauthenticated.
JOLPICA_MIN_INTERVAL_S = 0.3

OPENF1_BASE_URL = "https://api.openf1.org/v1"
# OpenF1 rate limit: 3 req/s, 30 req/min.
OPENF1_MIN_INTERVAL_S = 0.4
OPENF1_LIVE_POLL_INTERVAL_S = 18

OPEN_METEO_BASE_URL = "https://api.open-meteo.com/v1/forecast"

# Not in cache/: unlike everything else there, this can't be regenerated by
# re-fetching — it's the accumulated record of what the model predicted
# *before* each session's outcome was known.
TRACKING_DB_PATH = DATA_DIR / "tracking.db"

for _d in (
    DATA_DIR,
    CACHE_DIR,
    MODELS_DIR,
    JOLPICA_CACHE_DIR,
    FASTF1_CACHE_DIR,
    OPENF1_CACHE_DIR,
    OPEN_METEO_CACHE_DIR,
):
    _d.mkdir(parents=True, exist_ok=True)
