"""config.py — paths, env loading, and shared constants."""

import os
from pathlib import Path

from dotenv import load_dotenv

load_dotenv()

PROJECT_ROOT = Path(__file__).resolve().parents[2]
DATA_DIR = PROJECT_ROOT / "data"
CACHE_DIR = DATA_DIR / "cache"
MODELS_DIR = PROJECT_ROOT / "models"
FRONTEND_DIST_DIR = PROJECT_ROOT / "frontend" / "dist"

# Public, read-only deployment — unset/false everywhere else, which
# reproduces this app's original private-network-only behavior exactly
# (api/main.py's own CORS comment). No login gate: the public deployment
# has no admin surface reachable at all (routes.py::_admin_only 404s the
# one write endpoint regardless), so there's nothing a password would
# protect.
PUBLIC_MODE = os.getenv("PUBLIC_MODE", "false").lower() == "true"

JOLPICA_CACHE_DIR = CACHE_DIR / "jolpica"
FASTF1_CACHE_DIR = CACHE_DIR / "fastf1"
OPENF1_CACHE_DIR = CACHE_DIR / "openf1"
OPEN_METEO_CACHE_DIR = CACHE_DIR / "open_meteo"

CURRENT_SEASON = 2026  # bump each January

JOLPICA_BASE_URL = "https://api.jolpi.ca/ergast/f1"
JOLPICA_USER_AGENT = os.getenv(
    "JOLPICA_USER_AGENT", "F1Predictor/0.1 (personal project)"
)
# jolpica-f1 rate limit: 4 req/s, 500 req/hour, unauthenticated.
JOLPICA_MIN_INTERVAL_S = 0.3

OPENF1_BASE_URL = "https://api.openf1.org/v1"
# OpenF1 rate limit: 3 req/s, 30 req/min.
OPENF1_MIN_INTERVAL_S = 0.4
OPENF1_LIVE_POLL_INTERVAL_S = 18

OPEN_METEO_BASE_URL = "https://api.open-meteo.com/v1/forecast"

# Not in cache/: unlike everything else there, this can't be regenerated by
# re-fetching — it's the accumulated record of what the model predicted
# *before* each session's outcome was known.
TRACKING_DB_PATH = DATA_DIR / "tracking.db"

# Precomputed races/predictions/championship for the current season, so
# the public deployment never runs this project's live feature-building
# pipeline (Elo/team-strength replay, ranker predict, championship Monte
# Carlo sim) on an actual request -- same pattern as PL_Predictor's own
# public_snapshot.py. Generated by `python -m f1_predictor.public_snapshot`
# and committed like any other tracked file; the copy baked into the image
# is only the cold-start fallback -- a running process stays current by
# polling PUBLIC_SNAPSHOT_REFRESH_URL on a timer (api/routes.py::
# refresh_public_snapshot_from_remote, polled from api/main.py's lifespan)
# instead of waiting for a redeploy.
PUBLIC_SNAPSHOT_PATH = DATA_DIR / "public_snapshot.json"
PUBLIC_SNAPSHOT_REFRESH_URL = os.getenv(
    "PUBLIC_SNAPSHOT_REFRESH_URL",
    "https://raw.githubusercontent.com/Kevocado/F1_Predictor/main/data/public_snapshot.json",
)
PUBLIC_SNAPSHOT_POLL_SECONDS = int(os.getenv("PUBLIC_SNAPSHOT_POLL_SECONDS", "300"))

for _d in (
    DATA_DIR,
    CACHE_DIR,
    MODELS_DIR,
    JOLPICA_CACHE_DIR,
    FASTF1_CACHE_DIR,
    OPENF1_CACHE_DIR,
    OPEN_METEO_CACHE_DIR,
):
    _d.mkdir(parents=True, exist_ok=True)
